# i7-8700K (Coffee Lake) + RTX 3070
# Disk mounts are generated by hosts/desktop/disko.nix — do not add fileSystems here.
{ config, lib, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [];

  swapDevices = [];  # swapfile lives in the @swap btrfs subvolume (disko)

  fileSystems."/mnt/4TB-HDD0" = {
    device = "/dev/disk/by-uuid/FCA0F84FA0F811BE";
    fsType = "ntfs3";
    options = [ "uid=1000" "gid=100" "umask=022" "nofail" "x-systemd.automount" "x-systemd.idle-timeout=60" ];
  };

  fileSystems."/mnt/4TB-HDD1" = {
    device = "/dev/disk/by-uuid/FE64C7A164C75AD3";
    fsType = "ntfs3";
    options = [ "uid=1000" "gid=100" "umask=022" "nofail" "x-systemd.automount" "x-systemd.idle-timeout=60" ];
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
